name: Banyan IPFS External Adapter
description: A simple IPFS client for checking the status of files stored using the Banyan network.

node_identifier: Banyan_IPFS_EA

platforms:
  - Docker

parameters:
  - cid:
      type: string
      description: The CID of the file to check.
      required: true
